source 'https://github.com/CocoaPods/Specs.git'

target 'MBTNetworking', :exclusive => true do
  pod "MBTNetworking", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MBTNetworking", :path => "../"

end
